# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-17 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='书名')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='出版社名')),
            ],
        ),
        migrations.AddField(
            model_name='book2',
            name='pub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one2many.Publisher'),
        ),
    ]
