# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-31 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章主题')),
                ('category', models.CharField(max_length=20, verbose_name='博客的分类')),
                ('limit', models.CharField(max_length=10, verbose_name='权限')),
                ('introduce', models.CharField(max_length=90, verbose_name='博客简介')),
                ('content', models.TextField(verbose_name='博客内容')),
                ('created_time', models.DateField(auto_now_add=True, verbose_name='博客的创建时间')),
                ('modified_time', models.DateField(auto_now=True, verbose_name='博客的修改时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile')),
            ],
            options={
                'db_table': 'topic',
            },
        ),
    ]
