# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-07 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='score',
            field=models.IntegerField(default=0, verbose_name='分数'),
        ),
    ]
