# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-17 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20190717_0828'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table=None,
        ),
    ]
