# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-17 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_auto_20190717_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wife',
            name='name',
            field=models.CharField(max_length=30, verbose_name='作者妻子'),
        ),
    ]
