# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-16 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20190716_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='book',
            name='market_price',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=7, verbose_name='零售价'),
        ),
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.IntegerField(default=1, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='作者名'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='出版时间'),
        ),
    ]
